config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :phrases, only: [:index, :create, :destroy]

  post "/mark_favorite/:id" => "phrases#mark_favorite", as: :mark_favorite

  root to: "phrases#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :phrase

  validates_uniqueness_of :user_id, scope: :phrase_id
end

app/models/phrase.rb
class Phrase < ApplicationRecord
  validates_presence_of :text
  belongs_to :user
  has_many :favorites
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  has_many :phrases
  has_many :favorites
  has_many :fave_phrases, through: :favorites, source: :phrase

  def admin?
    role == "admin"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  before_action :set_phrase, only: [:mark_favorite, :destroy]
  def index
    @phrases = Phrase.all.reverse
  end

  def create
    @phrase = Phrase.new(phrase_params)
    @phrase.user = current_user
    @phrase.save
    redirect_to root_path
  end

  def mark_favorite
    @action = CreatesFavorite.new(user: current_user, phrase: @phrase)
    @action.create
    redirect_to root_path
  end

  def destroy 
    @phrase.destroy if current_user.phrases.include? @phrase
    redirect_to root_path
  end

  private

  def phrase_params
    params.require(:phrase).permit(:text)
  end

  def set_phrase
    @phrase = Phrase.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phrases_helper.rb
module PhrasesHelper
end

app/helpers/view_helper.rb
module ViewHelper
  def link_to_favorite phrase
    link_to mark_favorite_path(phrase), class: "btn btn-xs btn-primary", method: :post do
      link = []
      link.push phrase.favorites.count
      link.push icon("heart#{'-o' unless current_user.fave_phrases.include?(phrase)}")
      link.push current_user.fave_phrases.include?(phrase) ? "Unfavorite" : "Favorite"
      link.map(&:to_s).join(" ").html_safe
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phraser</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/phrases/create.html.erb
<h1>Phrases#create</h1>
<p>Find me in app/views/phrases/create.html.erb</p>

app/views/phrases/index.html.slim
.container style="width: 1000px;" 
  h2.text-center Phrases
  br
  .row
    .col-xs-6
      = form_for Phrase.new do |f|
        .form-group
          = f.text_area :text, class: "form-control", require: true, placeholder: "Enter phrase"
        .form-group
          = f.submit "Create Phrase", class: 'btn btn-success width-100'
        .form-group
          = link_to "Logout", destroy_user_session_path, class: "btn btn-danger width-100", method: :delete
          - if current_user.admin?
            .form-group
              = link_to "Administrator", rails_admin_path, class: "btn btn-info width-100"
    .col-xs-6.well
      - if @phrases.present?
        - @phrases.each do |phrase|
          blockquote
            p = phrase.text
            small 
              = phrase.user.name
              br 
              = "#{distance_of_time_in_words_to_now(phrase.created_at)} ago"
              br
              br
              = link_to_favorite(phrase)
              - if current_user.phrases.include? phrase
                = link_to "#{icon('trash', 'Delete')}".html_safe, phrase_path(phrase), class: "btn btn-xs btn-danger", style: "margin-left: 5px;", method: :delete
      - else
        p No saved Phrases